# Generated by Django 3.0.4 on 2020-08-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodiagnosis', '0003_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Correlated_Resport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodiagnosis.Report')),
                ('Symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodiagnosis.Symptom')),
            ],
        ),
    ]
