# Generated by Django 3.0.4 on 2020-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodiagnosis', '0005_auto_20200829_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_titile',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
