# Generated by Django 3.0.4 on 2020-08-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodiagnosis', '0006_report_report_titile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correlated_report',
            old_name='Report',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='correlated_report',
            old_name='Symptom',
            new_name='symptom',
        ),
    ]
