# Generated by Django 3.0.4 on 2020-08-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodiagnosis', '0007_auto_20200829_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_titile',
            new_name='report_title',
        ),
    ]
