# Generated by Django 3.0.4 on 2020-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200703_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='province',
            field=models.CharField(default='damascus', max_length=255),
            preserve_default=False,
        ),
    ]
