# Generated by Django 3.0.4 on 2020-07-04 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_clinic_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('Patient', models.ForeignKey(limit_choices_to={'groups__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Clinic')),
            ],
        ),
    ]
