# Generated by Django 3.0.4 on 2020-09-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='activated',
            field=models.IntegerField(default=0),
        ),
    ]
