# Generated by Django 3.0.4 on 2020-09-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clinic_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='activated',
        ),
    ]
