# Generated by Django 3.0.4 on 2020-09-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_clinic_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
