# Generated by Django 3.0.4 on 2020-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_clinic_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='creation_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
